"""new fields in user table

Revision ID: 407c5227f7d1
Revises: e0edcef218de
Create Date: 2020-07-08 18:29:53.193437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407c5227f7d1'
down_revision = 'e0edcef218de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
